[package]
name = "opentelemetry-honeycomb"
version = "0.1.0"
authors = ["David A. Ramos <ramos@cs.stanford.edu>"]
repository = "https://github.com/ramosbugs/opentelemetry-honeycomb-rs"
description = "Unofficial OpenTelemetry Exporter for Honeycomb"
license = "MIT"
edition = "2018"

[dependencies]
async-std = "1.8"
async-trait = "0.1"
chrono = "0.4"
derivative = "2.1"
futures = "0.3"
hazy = "0.1"
# Include unmerged changes to support flushing and various async improvements.
libhoney-rust = { git = "https://github.com/ramosbugs/libhoney-rust", rev = "f0751252e28f27064bc8bac8c44f05b74a19c25c" }
log = "0.4"
opentelemetry = "0.11"
serde_json = "1.0"
thiserror = "1.0"
tokio = { version = "1.0", features = ["rt"] }
